disabled_rules:
  - trailing_whitespace
  - todo
  - line_length
  - accessibility_label_for_image
  - file_length

opt_in_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button

identifier_name:
  min_length:
    warning: 1
    error: 1
