//
//  Themes.swift
//  Echo
//
//  Created by Will Wade on 17/08/2024.
//

import Foundation
extension Theme {
    static let themes: [Theme] = [
        Theme(name: "Light",
              highlightColor: "Black",
              highlightOpacity: 1.0,
              isHighlightTextBold: false,
              entriesColor: "Orange",
              entriesOpacity: 1.0,
              messageBarColorName: "Black",
              messageBarBackgroundColorName: "Mint",
              messageBarTextColorName: "Yellow",
              messageBarTextOpacity: 1.0,
              messageBarBackgroundOpacity: 1.0,
              messageBarFontSize: 16),
        
        Theme(name: "Light Bold",
              highlightColor: "Black",
              highlightOpacity: 1.0,
              isHighlightTextBold: true,
              entriesColor: "Orange",
              entriesOpacity: 1.0,
              messageBarColorName: "Black",
              messageBarBackgroundColorName: "Mint",
              messageBarTextColorName: "Yellow",
              messageBarTextOpacity: 1.0,
              messageBarBackgroundOpacity: 1.0,
              messageBarFontSize: 16),

        Theme(name: "Grey Red",
              highlightColor: "Red",
              highlightOpacity: 1.0,
              isHighlightTextBold: false,
              entriesColor: "Black",
              entriesOpacity: 1.0,
              messageBarColorName: "Red",
              messageBarBackgroundColorName: "Light Gray",
              messageBarTextColorName: "Gray",
              messageBarTextOpacity: 1.0,
              messageBarBackgroundOpacity: 1.0,
              messageBarFontSize: 16),

        Theme(name: "Yellow on Black",
              highlightColor: "Gray",
              highlightOpacity: 1.0,
              isHighlightTextBold: false,
              entriesColor: "Black",
              entriesOpacity: 1.0,
              messageBarColorName: "Black",
              messageBarBackgroundColorName: "Yellow",
              messageBarTextColorName: "Gray",
              messageBarTextOpacity: 1.0,
              messageBarBackgroundOpacity: 1.0,
              messageBarFontSize: 16),

        Theme(name: "Black on Yellow",
              highlightColor: "Yellow",
              highlightOpacity: 1.0,
              isHighlightTextBold: false,
              entriesColor: "Yellow",
              entriesOpacity: 1.0,
              messageBarColorName: "Yellow",
              messageBarBackgroundColorName: "Black",
              messageBarTextColorName: "Yellow",
              messageBarTextOpacity: 1.0,
              messageBarBackgroundOpacity: 1.0,
              messageBarFontSize: 16),

        Theme(name: "Mint",
              highlightColor: "Mint",
              highlightOpacity: 1.0,
              isHighlightTextBold: false,
              entriesColor: "Black",
              entriesOpacity: 1.0,
              messageBarColorName: "Mint",
              messageBarBackgroundColorName: "White",
              messageBarTextColorName: "Mint",
              messageBarTextOpacity: 1.0,
              messageBarBackgroundOpacity: 1.0,
              messageBarFontSize: 16),

        Theme(name: "Dark",
              highlightColor: "Black",
              highlightOpacity: 1.0,
              isHighlightTextBold: false,
              entriesColor: "Orange",
              entriesOpacity: 1.0,
              messageBarColorName: "Black",
              messageBarBackgroundColorName: "Black",
              messageBarTextColorName: "Yellow",
              messageBarTextOpacity: 1.0,
              messageBarBackgroundOpacity: 1.0,
              messageBarFontSize: 16),
        
        Theme(name: "System Default",
              highlightColor: "System Default",
              highlightOpacity: 1.0,
              isHighlightTextBold: false,
              entriesColor: "System Default",
              entriesOpacity: 0.5,
              messageBarColorName: "System Default",
              messageBarBackgroundColorName: "Light Gray",
              messageBarTextColorName: "System Default",
              messageBarTextOpacity: 1.0,
              messageBarBackgroundOpacity: 1.0,
              messageBarFontSize: 16)
    ]
}

