//
//  UIKeyboardHIDUsage.swift
//  Echo
//
//  Created by Gavin Henderson on 15/11/2023.
//

import Foundation
import UIKit

extension UIKeyboardHIDUsage {
    var description: String {
        switch self {
        case .keyboard0:
            return "0"
        case .keyboardErrorRollOver:
            return "UNKNOWN"
        case .keyboardPOSTFail:
            return "UNKNOWN"
        case .keyboardErrorUndefined:
            return "UNKNOWN"
        case .keyboardA:
            return "a"
        case .keyboardB:
            return "b"
        case .keyboardC:
            return "c"
        case .keyboardD:
            return "d"
        case .keyboardE:
            return "e"
        case .keyboardF:
            return "f"
        case .keyboardG:
            return "g"
        case .keyboardH:
            return "h"
        case .keyboardI:
            return "i"
        case .keyboardJ:
            return "j"
        case .keyboardK:
            return "k"
        case .keyboardL:
            return "l"
        case .keyboardM:
            return "m"
        case .keyboardN:
            return "n"
        case .keyboardO:
            return "o"
        case .keyboardP:
            return "p"
        case .keyboardQ:
            return "q"
        case .keyboardR:
            return "r"
        case .keyboardS:
            return "s"
        case .keyboardT:
            return "t"
        case .keyboardU:
            return "u"
        case .keyboardV:
            return "v"
        case .keyboardW:
            return "w"
        case .keyboardX:
            return "x"
        case .keyboardY:
            return "y"
        case .keyboardZ:
            return "z"
        case .keyboard1:
            return "1"
        case .keyboard2:
            return "2"
        case .keyboard3:
            return "3"
        case .keyboard4:
            return "4"
        case .keyboard5:
            return "5"
        case .keyboard6:
            return "6"
        case .keyboard7:
            return "7"
        case .keyboard8:
            return "8"
        case .keyboard9:
            return "9"
        case .keyboardReturnOrEnter:
            return "<ENTER>"
        case .keyboardEscape:
            return "<ESC>"
        case .keyboardDeleteOrBackspace:
            return "<BACKSPACE>"
        case .keyboardTab:
            return "<TAB>"
        case .keyboardSpacebar:
            return "<SPACE BAR>"
        case .keyboardHyphen:
            return "-"
        case .keyboardEqualSign:
            return "="
        case .keyboardOpenBracket:
            return "("
        case .keyboardCloseBracket:
            return ")"
        case .keyboardBackslash:
            return "\\"
        case .keyboardNonUSPound:
            return "£"
        case .keyboardSemicolon:
            return ";"
        case .keyboardQuote:
            return "\""
        case .keyboardGraveAccentAndTilde:
            return "~"
        case .keyboardComma:
            return ","
        case .keyboardPeriod:
            return "."
        case .keyboardSlash:
            return "/"
        case .keyboardCapsLock:
            return "<CAPS>"
        case .keyboardF1:
            return "F1"
        case .keyboardF2:
            return "F2"
        case .keyboardF3:
            return "F3"
        case .keyboardF4:
            return "F4"
        case .keyboardF5:
            return "F5"
        case .keyboardF6:
            return "F6"
        case .keyboardF7:
            return "F7"
        case .keyboardF8:
            return "F8"
        case .keyboardF9:
            return "F9"
        case .keyboardF10:
            return "F10"
        case .keyboardF11:
            return "F11"
        case .keyboardF12:
            return "UNKNOWN"
        case .keyboardPrintScreen:
            return "<PRINT>"
        case .keyboardScrollLock:
            return "<SCROLL LOCK>"
        case .keyboardPause:
            return "<PAUSE>"
        case .keyboardInsert:
            return "<INSERT>"
        case .keyboardHome:
            return "<HOME>"
        case .keyboardPageUp:
            return "<PAGE UP>"
        case .keyboardDeleteForward:
            return "<DEL FORWARD>"
        case .keyboardEnd:
            return "<END>"
        case .keyboardPageDown:
            return "<PAGE DOWN>"
        case .keyboardRightArrow:
            return "<RIGHT ARROW>"
        case .keyboardLeftArrow:
            return "<LEFT ARROW>"
        case .keyboardDownArrow:
            return "<DOWN ARROW>"
        case .keyboardUpArrow:
            return "<UP ARROW>"
        case .keypadNumLock:
            return "<NUM LOCK>"
        case .keypadSlash:
            return "/"
        case .keypadAsterisk:
            return "*"
        case .keypadHyphen:
            return "-"
        case .keypadPlus:
            return "+"
        case .keypadEnter:
            return "<ENTER>"
        case .keypad1:
            return "1"
        case .keypad2:
            return "2"
        case .keypad3:
            return "3"
        case .keypad4:
            return "4"
        case .keypad5:
            return "5"
        case .keypad6:
            return "6"
        case .keypad7:
            return "7"
        case .keypad8:
            return "8"
        case .keypad9:
            return "9"
        case .keypad0:
            return "0"
        case .keypadPeriod:
            return "."
        case .keyboardNonUSBackslash:
            return "\\"
        case .keyboardApplication:
            return "UNKNOWN"
        case .keyboardPower:
            return "UNKNOWN"
        case .keypadEqualSign:
            return "="
        case .keyboardF13:
            return "F13"
        case .keyboardF14:
            return "F14"
        case .keyboardF15:
            return "F15"
        case .keyboardF16:
            return "F16"
        case .keyboardF17:
            return "F17"
        case .keyboardF18:
            return "F18"
        case .keyboardF19:
            return "F19"
        case .keyboardF20:
            return "F20"
        case .keyboardF21:
            return "F21"
        case .keyboardF22:
            return "F22"
        case .keyboardF23:
            return "F23"
        case .keyboardF24:
            return "F24"
        case .keyboardExecute:
            return "UNKNOWN"
        case .keyboardHelp:
            return "UNKNOWN"
        case .keyboardMenu:
            return "UNKNOWN"
        case .keyboardSelect:
            return "UNKNOWN"
        case .keyboardStop:
            return "UNKNOWN"
        case .keyboardAgain:
            return "UNKNOWN"
        case .keyboardUndo:
            return "<UNDO>"
        case .keyboardCut:
            return "<CUT>"
        case .keyboardCopy:
            return "<COPY>"
        case .keyboardPaste:
            return "<PASTE>"
        case .keyboardFind:
            return "<FIND>"
        case .keyboardMute:
            return "<MUTE>"
        case .keyboardVolumeUp:
            return "<VOL UP>"
        case .keyboardVolumeDown:
            return "<VOL DOWN>"
        case .keyboardLockingCapsLock:
            return "<CAPS LOCK>"
        case .keyboardLockingNumLock:
            return "<NUM LOCK>"
        case .keyboardLockingScrollLock:
            return "<SCROLL LOCK>"
        case .keypadComma:
            return ","
        case .keypadEqualSignAS400:
            return "UNKNOWN"
        case .keyboardInternational1:
            return "UNKNOWN"
        case .keyboardInternational2:
            return "UNKNOWN"
        case .keyboardInternational3:
            return "UNKNOWN"
        case .keyboardInternational4:
            return "UNKNOWN"
        case .keyboardInternational5:
            return "UNKNOWN"
        case .keyboardInternational6:
            return "UNKNOWN"
        case .keyboardInternational7:
            return "UNKNOWN"
        case .keyboardInternational8:
            return "UNKNOWN"
        case .keyboardInternational9:
            return "UNKNOWN"
        case .keyboardLANG1:
            return "UNKNOWN"
        case .keyboardLANG2:
            return "UNKNOWN"
        case .keyboardLANG3:
            return "UNKNOWN"
        case .keyboardLANG4:
            return "UNKNOWN"
        case .keyboardLANG5:
            return "UNKNOWN"
        case .keyboardLANG6:
            return "UNKNOWN"
        case .keyboardLANG7:
            return "UNKNOWN"
        case .keyboardLANG8:
            return "UNKNOWN"
        case .keyboardLANG9:
            return "UNKNOWN"
        case .keyboardAlternateErase:
            return "UNKNOWN"
        case .keyboardSysReqOrAttention:
            return "UNKNOWN"
        case .keyboardCancel:
            return "<CANCEL>"
        case .keyboardClear:
            return "<CLEAR>"
        case .keyboardPrior:
            return "UNKNOWN"
        case .keyboardReturn:
            return "<RETURN>"
        case .keyboardSeparator:
            return "UNKNOWN"
        case .keyboardOut:
            return "UNKNOWN"
        case .keyboardOper:
            return "UNKNOWN"
        case .keyboardClearOrAgain:
            return "UNKNOWN"
        case .keyboardCrSelOrProps:
            return "UNKNOWN"
        case .keyboardExSel:
            return "UNKNOWN"
        case .keyboardLeftControl:
            return "<CONTROL>"
        case .keyboardLeftShift:
            return "<SHIFT>"
        case .keyboardLeftAlt:
            return "<ALT>"
        case .keyboardLeftGUI:
            return "UNKNOWN"
        case .keyboardRightControl:
            return "<CONTROL>"
        case .keyboardRightShift:
            return "<SHIFT>"
        case .keyboardRightAlt:
            return "<ALT>"
        case .keyboardRightGUI:
            return "UNKNOWN"
        case .keyboard_Reserved:
            return "UNKNOWN"
        @unknown default:
            return "UNKNOWN"
        }
    }
}
